### ISSUE TITLE
Is the project still active? #Help connecting to a WSS

### ISSUE THREAD

**Issue by arvanus** [andremussche/DelphiWebsockets#35]
(Is the author still working int his project?)

I'm trying to use this project's client to access this WS: wss://ws.blinktrade.com/trade/ from this link: https://blinktrade.com/docs/#blinktrade-sdk
But i`m unable to make it work, someone can give me a idea?

A got this error: 

> Exception class EIdHTTPProtocolException with message 'HTTP/1.1 404 Not Found

PS: I using Delphi 10.2 and XE7, here is my code copied from example:
```
//{$DEFINE WEBSOCKETSSL} enabled in the wsdefines.pas

  client := TIdHTTPWebsocketClient.Create(Self);
  client.Port := 443;
  client.Host := 'ws.blinktrade.com';
  client.WSResourceName := 'trade/';
  client.SocketIOCompatible := true;

  client.Connect; //error

```

I suspect the origin os the error comes from this lines in IdHTTPWebsocketClient
```
// Why is "/socket.io/1/" used? I don't know
        {$IFDEF WEBSOCKETSSL}
        sURL := Format('https://%s:%d/socket.io/1/', [Host, Port]);
        {$ELSE}
        sURL := Format('http://%s:%d/socket.io/1/', [Host, Port]);
        {$ENDIF}
```

Thanks for any help!

**Comment by andremussche** [comment]
I don't (actively) support this project anymore, see readme for 3rd party component (free version available)
https://github.com/andremussche/DelphiWebsockets/blob/master/README.md
